FROM node:18-alpine
WORKDIR /usr/app
COPY ./ /usr/app
RUN npm install
ARG PRIVATE_NPM_TOKEN
ARG DB_URL
ARG EXPOSE_PORT=3000
ENV SERVER_PORT = ${DB_URL}
ENV LOG_DATABASE_URL =${LOG_DATABASE_URL}
ENV NPM_TOKEN=${PRIVATE_NPM_TOKEN}
EXPOSE ${EXPOSE_PORT}
CMD ["npm", "start"]