FROM node:18-alpine
WORKDIR /usr/app
COPY ./ /usr/app
ARG PRIVATE_NPM_TOKEN
ARG DB_URL
ARG EXPOSE_PORT=3000
ARG LOGGER_ENV
ENV SERVER_PORT = ${DB_URL}
ENV LOG_DATABASE_URL =${LOG_DATABASE_URL}
ENV DB_LOGGER_ENVIORMENT=${LOGGER_ENV}
ENV NPM_TOKEN=${PRIVATE_NPM_TOKEN}
RUN npm install
EXPOSE ${EXPOSE_PORT}
CMD ["npm", "start"]