version: "3"

services:
  logger-service:
    environment:
      - LOG_DATABASE_URL = ${LOG_DATABASE_URL}
      - LOGGER_PORT = ${LOGGER_PORT}
    image: ghcr.io/bednaz98/db-logger:latest
    ports:
      - ${LOGGER_PORT}:${LOGGER_PORT}
