services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD= {{MYSQL_ROOT_PASSWORD}}
    ports:
      - {{ SQL_PORT }}:3306
    restart: always
  logger-service:
    environment:
      - LOG_DATABASE_URL= mysql://root:{{MYSQL_ROOT_PASSWORD}}@localhost:{{ SQL_PORT }}/log
      - LOGGER_PORT= {{ LOGGER_PORT }}
      - DB_LOGGER_ENVIORMENT= {{ LOGGER_ENV }}
    image: ghcr.io/bednaz98/db-logger:main
    ports:
      - {{ LOGGER_PORT }}:{{ LOGGER_PORT }}
    restart: always
    depends_on:
      - database